/* Fees & Payments: balances overview, payment history, fee structure, receipts. */
(function () {
  'use strict';
  const SC = window.SC; const esc = SC.esc;
  const FEE_TYPES = [['registration', 'Registration fee'], ['tuition', 'Tuition fee'], ['examination', 'Examination fee'], ['other', 'Other fee']];
  const docColor = () => `--doc-color:${SC.state.school.primary_color || '#0B6E4F'}`;

  // ------------------------------------------------------------ receipt
  function receiptHtml(r) {
    const s = r.school;
    return `<div class="sc-doc sc-receipt" style="${docColor()}"><div class="hd"><span class="lg">${esc(SC.schoolInitials(s))}${s.has_logo ? `<img src="${SC.logoUrl(s.id)}" alt="" onerror="this.remove()">` : ''}</span><div><h4>${esc(s.name)}</h4><div class="meta">${esc([s.address, s.phone, s.email].filter(Boolean).join(' · '))}</div></div></div>
      <div class="title">PAYMENT RECEIPT</div><div class="meta" style="text-align:center;margin-bottom:10px">Receipt No. <b style="color:#111">${esc(r.receipt_no)}</b></div>
      <table><tr><td>Date</td><td>${SC.date(r.payment_date)}</td></tr><tr><td>Student</td><td>${esc(r.student.name)}</td></tr><tr><td>Student ID</td><td>${esc(r.student.admission_no)}</td></tr><tr><td>Class</td><td>${esc(r.student.class_name)}</td></tr>
      <tr><td>Payment method</td><td>${esc(r.method)}</td></tr><tr><td>Reference / transaction no.</td><td>${esc(r.reference || '—')}</td></tr><tr><td>Received by</td><td>${esc(r.received_by || '—')}</td></tr></table>
      <div class="amt"><span class="meta">Amount paid</span><b>${SC.num(r.amount)} ${esc(r.currency)}</b></div>
      <table><tr><td>Total fees</td><td>${SC.num(r.total_fees)} ${esc(r.currency)}</td></tr><tr><td>Paid to date</td><td>${SC.num(r.paid_to_date)} ${esc(r.currency)}</td></tr><tr><td>Remaining balance</td><td style="color:${r.balance > 0 ? '#c0392b' : '#12805C'}">${SC.num(r.balance)} ${esc(r.currency)}</td></tr></table>
      ${r.notes ? `<div class="meta" style="margin-top:8px">Notes: ${esc(r.notes)}</div>` : ''}<div class="foot">${esc(r.footer || '')}<br>This receipt was generated by the school system and is valid without a signature.</div></div>`;
  }
  SC.receiptModal = async (paymentId) => {
    const { receipt } = await SC.api.get(`/payments/${paymentId}/receipt`);
    const back = SC.modal(`Receipt ${receipt.receipt_no}`, `<div class="sc-doc-stage" id="rcptStage">${receiptHtml(receipt)}</div>`, {
      footer: '<button class="sc-btn ghost" data-close2>Close</button><button class="sc-btn ghost" data-pdf><i class="fa-solid fa-file-pdf"></i> Download PDF</button><button class="sc-btn primary" data-print><i class="fa-solid fa-print"></i> Print receipt</button>',
    });
    back.querySelector('[data-close2]').onclick = () => SC.closeModal();
    back.querySelector('[data-print]').onclick = () => SC.print(`<div style="display:flex;justify-content:center">${receiptHtml(receipt)}</div>`);
    back.querySelector('[data-pdf]').onclick = async (e) => {
      const b = e.currentTarget; b.disabled = true;
      try { await SC.pdf(back.querySelector('.sc-receipt'), `Receipt-${receipt.receipt_no}.pdf`, { format: 'a5', margin: 10 }); SC.toast('Receipt downloaded.'); } catch (err) { SC.fail(err); } finally { b.disabled = false; }
    };
  };

  // ------------------------------------------------------------ record payment
  SC.payModal = async ({ studentId = null, onDone } = {}) => {
    const methods = SC.state.settings.payment_methods || ['Cash', 'Bank', 'Mobile Money', 'Card', 'Other'];
    let student = null;
    if (studentId) {
      const [{ student: s }, fees] = await Promise.all([SC.api.get(`/students/${studentId}`), SC.api.get(`/students/${studentId}/fees`)]);
      student = { id: s.id, name: s.full_name, admission_no: s.admission_no, balance: fees.summary.balance, total: fees.summary.total, cls: s.class ? SC.classLabel(s.class) : '' };
    }
    const back = SC.formModal({
      title: 'Record payment', size: 'wide', submit: 'Save payment & create receipt',
      body: `<div id="stuBox">${student ? '' : `<div class="sc-field"><label for="sQ">Student <span class="req">*</span></label><input class="sc-input" id="sQ" type="search" placeholder="Type the student's name or ID…" autocomplete="off"><div id="sRes" class="sc-list"></div></div>`}</div>
        <div id="stuInfo"></div>
        <div class="cols">${SC.f.input('amount', 'Amount', { type: 'number', required: true, attr: { min: 1, step: '0.01' }, placeholder: '0' })}${SC.f.input('payment_date', 'Payment date', { type: 'date', required: true, value: SC.today(), attr: { max: SC.today() } })}</div>
        <div class="cols">${SC.f.select('method', 'Payment method', methods.map((m) => [m, m]), { required: true, value: methods[0], noBlank: true })}${SC.f.input('reference', 'Reference / transaction number', { placeholder: 'Required for Bank, Mobile Money and Card' })}</div>
        <div class="cols">${SC.f.input('received_by', 'Received by', { value: SC.state.user.name, attr: { readonly: true } })}${SC.f.input('notes', 'Notes', { placeholder: 'Optional' })}</div>`,
      onSubmit: async (f) => {
        if (!student) throw new Error('Please choose the student who is paying.');
        const r = await SC.api.post('/payments', { student_id: student.id, amount: Number(f.amount), payment_date: f.payment_date, method: f.method, reference: f.reference, notes: f.notes });
        SC.closeModal();
        const done = SC.modal('Payment recorded', `<div class="sc-center"><div class="sc-empty" style="padding:.5rem 0"><div class="ico" style="background:var(--sc-ok-bg);color:var(--sc-ok)"><i class="fa-solid fa-circle-check"></i></div><h4>Payment recorded successfully.</h4><p style="margin:0 auto">Receipt <b>${esc(r.receipt_no)}</b> · Remaining balance <b>${SC.money(r.balance)}</b></p></div></div>`, {
          footer: '<button class="sc-btn ghost" data-x>Close</button><button class="sc-btn primary" data-r><i class="fa-solid fa-receipt"></i> View / Print receipt</button>' });
        done.querySelector('[data-x]').onclick = () => { SC.closeModal(); if (onDone) onDone(r); };
        done.querySelector('[data-r]').onclick = () => { SC.closeModal(); SC.receiptModal(r.id); if (onDone) onDone(r); };
      },
    });
    const info = back.querySelector('#stuInfo');
    const showStudent = (s) => {
      student = s;
      info.innerHTML = `<div class="sc-alert info"><i class="fa-solid fa-user-graduate"></i><div class="sc-spread" style="flex:1"><div><b>${esc(s.name)}</b> · ${esc(s.admission_no)}${s.cls ? ' · ' + esc(s.cls) : ''}<div class="sc-small">Total fees ${SC.money(s.total)} · Outstanding balance <b>${SC.money(s.balance)}</b></div></div>${studentId ? '' : '<button type="button" class="sc-btn ghost sm" data-change>Change</button>'}</div></div>`;
      const amt = back.querySelector('[name=amount]'); amt.max = s.balance; if (s.balance > 0) amt.placeholder = `Up to ${SC.num(s.balance)}`;
      const box = back.querySelector('#stuBox'); if (box && !studentId) box.classList.add('sc-hide');
      const ch = info.querySelector('[data-change]'); if (ch) ch.onclick = () => { student = null; info.innerHTML = ''; box.classList.remove('sc-hide'); back.querySelector('#sQ').focus(); };
    };
    if (student) showStudent(student);
    else {
      const run = SC.debounce(async () => {
        const q = back.querySelector('#sQ').value.trim(); const box = back.querySelector('#sRes');
        if (q.length < 2) { box.innerHTML = ''; return; }
        try {
          const d = await SC.api.get('/fees/overview' + SC.qs({ q, limit: 6 }));
          box.innerHTML = d.students.length ? d.students.map((s) => `<div class="sc-spread"><div><b>${esc(s.full_name)}</b><div class="sc-small sc-muted">${esc(s.admission_no)} · ${esc(s.class_name)} · Balance ${SC.num(s.balance)}</div></div><button type="button" class="sc-btn primary sm" data-pick="${s.student_id}" data-n="${esc(s.full_name)}" data-a="${esc(s.admission_no)}" data-c="${esc(s.class_name)}" data-b="${s.balance}" data-t="${s.total}">Choose</button></div>`).join('') : '<div class="sc-muted sc-small" style="padding:.5rem 0">No student found.</div>';
        } catch (e) { box.innerHTML = `<div class="sc-form-error show">${esc(e.message)}</div>`; }
      }, 250);
      back.querySelector('#sQ').addEventListener('input', run);
      back.addEventListener('click', (e) => { const b = e.target.closest('[data-pick]'); if (b) showStudent({ id: Number(b.dataset.pick), name: b.dataset.n, admission_no: b.dataset.a, cls: b.dataset.c, balance: Number(b.dataset.b), total: Number(b.dataset.t) }); });
    }
  };

  // ------------------------------------------------------------ fee structure modal
  async function feeModal(f, done) {
    const lk = await SC.lookups(); const isEdit = !!f;
    SC.formModal({
      title: isEdit ? 'Edit fee' : 'Add fee', submit: isEdit ? 'Save changes' : 'Add fee',
      body: `<div class="cols">${SC.f.input('name', 'Fee name', { required: true, value: f ? f.name : '', placeholder: 'e.g. Tuition — Term 1' })}${SC.f.select('fee_type', 'Fee type', FEE_TYPES, { required: true, value: f ? f.fee_type : 'tuition', noBlank: true })}</div>
        <div class="cols">${SC.f.input('amount', 'Amount', { type: 'number', required: true, value: f ? f.amount : '', attr: { min: 0, step: '0.01' } })}${SC.f.input('due_date', 'Due date', { type: 'date', value: f ? f.due_date || '' : '', hint: 'Unpaid fees become "Overdue" after this date.' })}</div>
        <div class="cols">${SC.f.select('class_id', 'Applies to', SC.opts.classes(lk, false), { value: f ? f.class_id || '' : '', placeholder: 'All classes' })}${isEdit ? '' : SC.f.select('academic_year_id', 'Academic year', SC.opts.years(lk), { value: (lk.years.find((y) => y.is_current) || {}).id, noBlank: true })}</div>`,
      onSubmit: async (v) => {
        const body = { name: v.name, fee_type: v.fee_type, amount: Number(v.amount), due_date: v.due_date || null, class_id: v.class_id || null, academic_year_id: v.academic_year_id };
        if (isEdit) await SC.api.put(`/fees/structures/${f.id}`, body); else await SC.api.post('/fees/structures', body);
        SC.closeModal(); SC.toast(isEdit ? 'Fee updated successfully.' : 'Fee added successfully.'); done();
      },
    });
  }

  async function paymentEditModal(p, done) {
    const methods = SC.state.settings.payment_methods;
    SC.formModal({
      title: `Edit payment ${p.receipt_no || ''}`, submit: 'Save changes',
      body: `<div class="sc-alert info"><i class="fa-solid fa-circle-info"></i><div>Changes to payments are recorded in the audit log.</div></div><div class="cols">${SC.f.input('amount', 'Amount', { type: 'number', required: true, value: p.amount, attr: { min: 0.01, step: '0.01' } })}${SC.f.input('payment_date', 'Payment date', { type: 'date', required: true, value: p.payment_date, attr: { max: SC.today() } })}</div>
        <div class="cols">${SC.f.select('method', 'Method', methods.map((m) => [m, m]), { value: p.method, noBlank: true })}${SC.f.input('reference', 'Reference', { value: p.reference || '' })}</div>${SC.f.input('notes', 'Notes', { value: p.notes || '' })}`,
      onSubmit: async (v) => { await SC.api.put(`/payments/${p.id}`, { ...v, amount: Number(v.amount) }); SC.closeModal(); SC.toast('Payment updated.'); done(); },
    });
  }

  // ------------------------------------------------------------ main screen
  SC.modules.fees = async (el, args, seg) => {
    const lk = await SC.lookups();
    let tab = 'overview'; const st = { q: '', class_id: '', status: '', page: 1, limit: 20 }; const pst = { q: '', method: '', from: '', to: '', page: 1, limit: 20 };
    const methods = SC.state.settings.payment_methods || [];
    el.innerHTML = `${SC.pageHead('Fees & Payments', 'Balances, payments, receipts and the fee structure', `${SC.can('fees.manage') || SC.can('announcements.manage') ? '<button class="sc-btn ghost" data-act="remind"><i class="fa-solid fa-paper-plane"></i> Send fee reminders</button>' : ''}${SC.can('fees.record') ? '<button class="sc-btn primary" data-act="pay"><i class="fa-solid fa-plus"></i> Record Payment</button>' : ''}`)}
      <div id="feeKpis"></div>
      <div class="sc-tabs" id="feeTabs"><button class="on" data-tab="overview">Student balances</button><button data-tab="payments">Payments & receipts</button>${SC.can('fees.manage') ? '<button data-tab="structure">Fee structure</button>' : ''}</div><div id="feeBody">${SC.skeleton(6)}</div>`;
    const body = el.querySelector('#feeBody');

    async function overview() {
      const d = await SC.api.get('/fees/overview' + SC.qs(st)); const s = d.summary;
      el.querySelector('#feeKpis').innerHTML = `<div class="sc-grid stats" style="margin-bottom:1.1rem">${SC.stat('fa-file-invoice-dollar', SC.money(s.total_fees), 'Total fees expected')}${SC.stat('fa-sack-dollar', SC.money(s.total_paid), 'Total collected', '', 'green')}${SC.stat('fa-scale-unbalanced', SC.money(s.outstanding), 'Outstanding', `${s.counts.overdue} overdue`, 'red')}${SC.stat('fa-users', `${s.counts.paid} / ${s.counts.partial} / ${s.counts.pending} / ${s.counts.overdue}`, 'Paid / Partial / Pending / Overdue', 'Students by status', 'blue')}</div>`;
      body.innerHTML = `<div class="sc-card"><div class="sc-toolbar"><input class="sc-input grow" id="oQ" type="search" placeholder="Search student name or ID…" value="${esc(st.q)}">
        <select class="sc-select" id="oClass"><option value="">All classes</option>${SC.opts.classes(lk, false).map((o) => `<option value="${o.v}" ${String(o.v) === String(st.class_id) ? 'selected' : ''}>${esc(o.l)}</option>`).join('')}</select>
        <select class="sc-select" id="oStatus"><option value="">Any status</option>${[['paid', 'Paid'], ['partial', 'Partially Paid'], ['pending', 'Pending'], ['overdue', 'Overdue']].map(([v, l]) => `<option value="${v}" ${st.status === v ? 'selected' : ''}>${l}</option>`).join('')}</select></div>
        ${SC.table([
          { label: 'Student', render: (r) => `<a href="#student/${r.student_id}" class="sc-person"><span><span class="nm" style="color:var(--sc-text)">${esc(r.full_name)}</span><div class="sb sc-muted">${esc(r.admission_no)}</div></span></a>` },
          { label: 'Class', render: (r) => esc(r.class_name) }, { label: 'Parent', render: (r) => `${esc(r.parent_name || '—')}<div class="sc-small sc-muted">${esc(r.parent_phone || '')}</div>` },
          { label: 'Total fees', cls: 'end', render: (r) => SC.num(r.total) }, { label: 'Paid', cls: 'end', render: (r) => SC.num(r.paid) }, { label: 'Balance', cls: 'end', render: (r) => `<b>${SC.num(r.balance)}</b>` },
          { label: 'Status', render: (r) => SC.chip(r.status) },
          { label: '', cls: 'end', render: (r) => SC.can('fees.record') && r.balance > 0 ? `<button class="sc-btn soft sm" data-act="paystu" data-id="${r.student_id}"><i class="fa-solid fa-plus"></i> Pay</button>` : '' },
        ], d.students, { empty: SC.empty('fa-coins', 'No students to show', st.q || st.status || st.class_id ? 'No student matches these filters.' : 'Register students and set a fee structure to see balances.') })}${SC.pager(d.page, d.limit, d.total)}</div>`;
      body.querySelector('#oQ').addEventListener('input', SC.debounce((e) => { st.q = e.target.value.trim(); st.page = 1; draw(); }, 300));
      body.querySelector('#oClass').addEventListener('change', (e) => { st.class_id = e.target.value; st.page = 1; draw(); });
      body.querySelector('#oStatus').addEventListener('change', (e) => { st.status = e.target.value; st.page = 1; draw(); });
    }
    async function payments() {
      el.querySelector('#feeKpis').innerHTML = '';
      const d = await SC.api.get('/payments' + SC.qs(pst));
      body.innerHTML = `<div class="sc-card"><div class="sc-toolbar"><input class="sc-input grow" id="pyQ" type="search" placeholder="Search student, receipt number or reference…" value="${esc(pst.q)}">
        <select class="sc-select" id="pyM"><option value="">All methods</option>${methods.map((m) => `<option ${pst.method === m ? 'selected' : ''}>${esc(m)}</option>`).join('')}</select>
        <input class="sc-input" id="pyF" type="date" value="${pst.from}" title="From date" aria-label="From date"><input class="sc-input" id="pyT" type="date" value="${pst.to}" title="To date" aria-label="To date"></div>
        <div class="sc-small sc-muted" style="margin-bottom:.6rem">${d.total} payment${d.total === 1 ? '' : 's'} · Total <b>${SC.money(d.sum)}</b></div>
        ${SC.table([
          { label: 'Date', render: (r) => SC.date(r.payment_date) }, { label: 'Receipt', render: (r) => `<b>${esc(r.receipt_no || '—')}</b>` },
          { label: 'Student', render: (r) => `<a href="#student/${r.student_id}">${esc(r.student_name)}</a><div class="sc-small sc-muted">${esc(r.admission_no)}</div>` },
          { label: 'Method', render: (r) => esc(r.method) }, { label: 'Reference', render: (r) => esc(r.reference || '—') }, { label: 'Received by', render: (r) => esc(r.received_by_name || '—') },
          { label: 'Amount', cls: 'end', render: (r) => `<b>${SC.num(r.amount)}</b>` },
          { label: '', cls: 'end', render: (r) => `<div class="sc-actions-cell"><button class="sc-btn ghost sm" data-act="receipt" data-id="${r.id}"><i class="fa-solid fa-receipt"></i> Receipt</button>${SC.can('fees.manage') ? `<button class="sc-btn ghost sm" data-act="editpay" data-id="${r.id}"><i class="fa-solid fa-pen"></i></button>` : ''}</div>` },
        ], d.payments, { empty: SC.empty('fa-receipt', 'No payments found', 'Payments you record will be listed here with their receipts.') })}${SC.pager(d.page, d.limit, d.total)}</div>`;
      body._pay = d.payments;
      const bindP = (id, k, ev = 'change') => body.querySelector(id).addEventListener(ev, (e) => { pst[k] = e.target.value.trim(); pst.page = 1; draw(); });
      body.querySelector('#pyQ').addEventListener('input', SC.debounce((e) => { pst.q = e.target.value.trim(); pst.page = 1; draw(); }, 300)); bindP('#pyM', 'method'); bindP('#pyF', 'from'); bindP('#pyT', 'to');
    }
    async function structure() {
      el.querySelector('#feeKpis').innerHTML = '';
      const d = await SC.api.get('/fees/structures');
      const total = d.structures.filter((x) => !x.class_id).reduce((s, x) => s + x.amount, 0);
      body.innerHTML = `<div class="sc-card"><div class="sc-card-head"><h3>Fee structure — current academic year</h3><div class="sc-actions"><button class="sc-btn primary sm" data-act="addfee"><i class="fa-solid fa-plus"></i> Add fee</button></div></div>
        <div class="sc-alert info" style="margin-bottom:1rem"><i class="fa-solid fa-circle-info"></i><div>A student's <b>total fees</b> is the sum of every fee that applies to their class. Fees for “All classes” add up to <b>${SC.money(total)}</b>. Balances update automatically when you change this list.</div></div>
        ${SC.table([{ label: 'Fee', render: (f) => `<b>${esc(f.name)}</b>` }, { label: 'Type', render: (f) => SC.cap(f.fee_type) }, { label: 'Applies to', render: (f) => f.class_id ? esc(SC.classLabel({ name: f.class_name, stream: f.class_stream })) : 'All classes' }, { label: 'Due date', render: (f) => f.due_date ? SC.date(f.due_date) : '—' }, { label: 'Amount', cls: 'end', render: (f) => `<b>${SC.num(f.amount)}</b>` },
          { label: '', cls: 'end', render: (f) => `<div class="sc-actions-cell"><button class="sc-btn ghost sm" data-act="editfee" data-id="${f.id}"><i class="fa-solid fa-pen"></i></button><button class="sc-btn danger-ghost sm" data-act="delfee" data-id="${f.id}" data-name="${esc(f.name)}"><i class="fa-solid fa-trash"></i></button></div>` }],
        d.structures, { empty: SC.empty('fa-list-check', 'No fees yet', 'Add registration, tuition, examination or other fees.', '<button class="sc-btn primary" data-act="addfee"><i class="fa-solid fa-plus"></i> Add fee</button>') })}</div>`;
      body._fees = d.structures;
    }
    async function draw() { body.style.opacity = '.6'; try { await ({ overview, payments, structure })[tab](); } catch (e) { body.innerHTML = SC.errorBox(e); } body.style.opacity = '1'; }

    el.querySelector('#feeTabs').addEventListener('click', (e) => { const b = e.target.closest('button'); if (!b) return; tab = b.dataset.tab; el.querySelectorAll('#feeTabs button').forEach((x) => x.classList.toggle('on', x === b)); body.innerHTML = SC.skeleton(6); draw(); });
    SC.delegate(el, {
      page: (b) => { (tab === 'overview' ? st : pst).page = Number(b.dataset.p); draw(); },
      pay: () => SC.payModal({ onDone: draw }), paystu: (b) => SC.payModal({ studentId: b.dataset.id, onDone: draw }),
      receipt: (b) => SC.receiptModal(b.dataset.id),
      editpay: (b) => paymentEditModal(body._pay.find((p) => String(p.id) === b.dataset.id), draw),
      addfee: () => feeModal(null, draw), editfee: (b) => feeModal(body._fees.find((f) => String(f.id) === b.dataset.id), draw),
      delfee: async (b) => { if (!(await SC.confirm({ title: 'Delete this fee?', message: `<b>${esc(b.dataset.name)}</b> will be removed and every affected student's balance will be recalculated. Payments already recorded are kept.`, confirmText: 'Yes, delete fee' }))) return; await SC.api.del(`/fees/structures/${b.dataset.id}`); SC.toast('Fee deleted.'); draw(); },
      remind: async () => {
        if (!(await SC.confirm({ title: 'Send fee reminders?', message: 'Every student with <b>overdue</b> fees gets a fee reminder that their parent sees in the portal. Students reminded in the last 7 days are skipped.', confirmText: 'Send reminders', danger: false, icon: 'fa-paper-plane' }))) return;
        const r = await SC.api.post('/fees/reminders'); SC.toast(r.sent ? `${r.sent} fee reminder${r.sent === 1 ? '' : 's'} sent.` : r.overdue ? 'Everyone with overdue fees was already reminded this week.' : 'No students have overdue fees. Nothing to send.');
      },
    });
    await draw();
    if (seg === 'receipt' && args[0]) { history.replaceState(null, '', '#fees'); SC.after(() => SC.receiptModal(args[0]).catch(SC.fail)); }
    if (args[0] === 'pay' && SC.can('fees.record')) { history.replaceState(null, '', '#fees'); SC.after(() => SC.payModal({ onDone: draw })); }
  };
})();
